config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.com/fall3d-suite/fall3d:
      branch: master
      repo: https://gitlab.com/fall3d-suite/fall3d
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.com/fall3d-suite/fall3d git:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-blue-cow.sh
        container: qc.acc_dorky-gamboge-peccary
  QC.Doc:
    repos:
      gitlab.com/fall3d-suite/fall3d find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-orange-dunker.sh
        container: qc.doc_lovely-smalt-devil
      gitlab.com/fall3d-suite/fall3d git:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-grey-maltese.sh
        container: qc.doc_muggy-sepia-argentino
      gitlab.com/fall3d-suite/fall3d markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-razzmatazz-seal.sh
        container: qc.doc_wimpy-alizarin-beaver
  QC.Lic:
    repos:
      gitlab.com/fall3d-suite/fall3d licensee:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-wisteria-abyssinian.sh
        container: qc.lic_scaly-wisteria-heron
  QC.Met:
    repos:
      gitlab.com/fall3d-suite/fall3d cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-indigo-cuscus.sh
        container: qc.met_scaly-thistle-hare
  QC.Sec:
    repos:
      gitlab.com/fall3d-suite/fall3d bandit:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-brown-toad.sh
        container: qc.sec_scaly-vermilion-frigatebird
  QC.Sty:
    repos:
      gitlab.com/fall3d-suite/fall3d flake8:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-pumpkin-hummingbird.sh
        container: qc.sty_gimpy-amethyst-whippet
  QC.Ver:
    repos:
      gitlab.com/fall3d-suite/fall3d get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-brown-heron.sh
        container: qc.ver_chewy-azure-mammoth
timeout: 5400
