config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.com/fall3d-suite/fall3d:
      branch: master
      repo: https://gitlab.com/fall3d-suite/fall3d
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.com/fall3d-suite/fall3d git:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-sapphire-ray.sh
        container: qc.acc_gloppy-cinnamon-kakapo
  QC.Doc:
    repos:
      gitlab.com/fall3d-suite/fall3d find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-tan-lizard.sh
        container: qc.doc_stealthy-sangria-crocodile
      gitlab.com/fall3d-suite/fall3d git:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-taupe-sponge.sh
        container: qc.doc_skinny-peach-alligator
      gitlab.com/fall3d-suite/fall3d markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-platinum-eleuth.sh
        container: qc.doc_greasy-sapphire-wolf
  QC.Lic:
    repos:
      gitlab.com/fall3d-suite/fall3d licensee:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-pink-uguisu.sh
        container: qc.lic_sloppy-grey-dalmatian
  QC.Met:
    repos:
      gitlab.com/fall3d-suite/fall3d cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-indigo-axolotl.sh
        container: qc.met_muzzy-malachite-dhole
  QC.Sec:
    repos:
      gitlab.com/fall3d-suite/fall3d bandit:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-ecru-duck.sh
        container: qc.sec_ready-gold-drever
  QC.Sty:
    repos:
      gitlab.com/fall3d-suite/fall3d flake8:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-tangerine-sheepdog.sh
        container: qc.sty_lanky-platinum-lemming
  QC.Ver:
    repos:
      gitlab.com/fall3d-suite/fall3d get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-myrtle-squid.sh
        container: qc.ver_surly-platinum-quail
timeout: 5400
