config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.com/fall3d-suite/fall3d:
      branch: master
      repo: https://gitlab.com/fall3d-suite/fall3d
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.com/fall3d-suite/fall3d git:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-cyan-pig.sh
        container: qc.acc_scaly-pink-gerbil
  QC.Doc:
    repos:
      gitlab.com/fall3d-suite/fall3d find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-orange-magpie.sh
        container: qc.doc_pokey-aquamarine-chameleon
      gitlab.com/fall3d-suite/fall3d git:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-burgundy-quail.sh
        container: qc.doc_cheeky-heliotrope-chihuahua
      gitlab.com/fall3d-suite/fall3d markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-myrtle-cuscus.sh
        container: qc.doc_shaggy-russet-antelope
  QC.Lic:
    repos:
      gitlab.com/fall3d-suite/fall3d licensee:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-tangerine-uguisu.sh
        container: qc.lic_trippy-lilac-rottweiler
  QC.Met:
    repos:
      gitlab.com/fall3d-suite/fall3d cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-malachite-caiman.sh
        container: qc.met_scummy-indigo-mastiff
  QC.Sec:
    repos:
      gitlab.com/fall3d-suite/fall3d bandit:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-sapphire-flounder.sh
        container: qc.sec_shaky-copper-jellyfish
  QC.Sty:
    repos:
      gitlab.com/fall3d-suite/fall3d flake8:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-turquoise-dingo.sh
        container: qc.sty_ugly-russet-rattlesnake
  QC.Ver:
    repos:
      gitlab.com/fall3d-suite/fall3d get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-gamboge-gorilla.sh
        container: qc.ver_slaphappy-azure-squirrel
timeout: 5400
